# ===============================================================
# 建议使用备用主题配置来配置 NexT
# 修改此文件可能会导致合并冲突
# 详见: https://theme-next.js.org/docs/getting-started/configuration
# ===============================================================
# 博客主题配置文件

# ---------------------------------------------------------------
# 主题核心配置设置
# ---------------------------------------------------------------

# 允许缓存内容生成
cache:
  enable: false

# 生成后删除不必要的文件
minify: false

# 自定义文件路径设置
# 在站点目录 source/_data 中创建自定义文件
custom_file_path:
  #head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  #postBodyStart: source/_data/post-body-start.njk
  #postBodyEnd: source/_data/post-body-end.njk
  #footer: source/_data/footer.njk
  #bodyEnd: source/_data/body-end.njk
  #variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  #style: source/_data/styles.styl


# ---------------------------------------------------------------
# 主题方案设置
# ---------------------------------------------------------------

# 可选主题方案
# scheme: Muse  # 当前使用 Muse 主题方案
# scheme: Mist  # 简洁版
# scheme: Pisces  # 双栏版
scheme: Gemini  # 双栏版(带阴影)

# 深色模式
darkmode: false  # 是否启用深色模式


# ---------------------------------------------------------------
# 网站信息设置
# ---------------------------------------------------------------

# 网站图标设置
favicon:
  small: /images/favicon-16x16-next.png  # 小图标
  medium: /images/favicon-32x32-next.png  # 中等图标
  apple_touch_icon: /images/apple-touch-icon-next.png  # 苹果设备图标
  safari_pinned_tab: /images/logo.svg  # Safari固定标签页图标

# 自定义 Logo (注意: 不支持 Mist 主题方案)
custom_logo: #/uploads/custom-logo.png

# 知识共享许可协议 4.0 设置
creative_commons:
  license: by-nc-sa  # 许可证类型：署名-非商业性使用-相同方式共享
  size: small  # 显示大小
  sidebar: false  # 是否在侧边栏显示
  post: false  # 是否在文章中显示

# ---------------------------------------------------------------
# 菜单设置
# ---------------------------------------------------------------

# 使用方法: `Key: /link/ || icon`
# Key 是菜单项名称，如果有翻译将使用翻译文本
menu:
  home: / || fa fa-home  # 首页
  # about: /about/ || fa fa-user  # 关于
  tags: /tags/ || fa fa-tags  # 标签
  categories: /categories/ || fa fa-th  # 分类
  archives: /archives/ || fa fa-archive  # 归档
  # study: /study/ || fa fa-book  # 学习
  # live: /live/ || fa fa-heart  # 生活

# 菜单图标和徽章设置
menu_settings:
  icons: true  # 是否显示图标
  badges: true  # 是否显示徽章

# ---------------------------------------------------------------
# 侧边栏设置
# ---------------------------------------------------------------

sidebar:
  position: left  # 侧边栏位置：左侧或右侧
  width_expanded: 320  # 展开时宽度
  width_dual_column: 240  # 双栏模式下的宽度
  display: post  # 显示方式：post(文章页面自动展开)|always(总是展开)|hide(点击展开)|remove(移除)
  padding: 18  # 内边距
  offset: 12  # 顶部偏移量

# 头像设置
avatar:
  url: /uploads/avatar.gif  # 头像图片地址
  rounded: false  # 是否显示圆形
  rotated: false  # 鼠标悬停是否旋转

# 侧边栏显示文章/分类/标签
site_state: true

# 社交链接设置
social:
  GitHub: https://github.com/sian-siyu/sian-siyu.github.io/ || fab fa-github  # GitHub链接
  #E-Mail: mailto:yourname@gmail.com || fa fa-envelope  # 邮箱链接
  #Weibo: https://weibo.com/yourname || fab fa-weibo  # 微博链接

# 社交图标设置
social_icons:
  enable: true  # 是否启用
  icons_only: true  # 是否只显示图标
  transition: true  # 是否启用过渡动画

# 友情链接设置
links_settings:
  icon: fa fa-globe  # 链接图标
  layout: block  # 布局方式：block(块级)|inline(行内)

# 目录设置
toc:
  enable: true  # 是否启用
  number: true  # 是否显示序号
  wrap: false  # 是否自动换行
  expand_all: false  # 是否展开所有目录
  max_depth: 6  # 最大目录深度

back2top: 
  enable: true # 是否启用返回顶部按钮
  # icon: fa fa-arrow-up  # 返回顶部按钮图标
  # sidebar: false # 是否在侧边栏显示返回顶部按钮
  scrollpercent: true # 是否显示滚动百分比

# ---------------------------------------------------------------
# 页脚设置
# ---------------------------------------------------------------

# 是否显示语言切换器
language_switcher: false


footer:
  # 建站年份
  # since: 2025

  # 页脚图标设置
  icon:
    name: fa fa-heart  # 图标名称
    animated: true  # 是否启用动画
    color: "#ff0000"  # 图标颜色

  # 版权信息
  copyright:  # 留空则使用 Hexo 配置中的作者信息

  # 是否显示"Powered by Hexo & NexT"
  powered: false

  # 备案信息设置
  beian:
    enable: false  # 是否启用备案信息
    icp:  # ICP备案号
    gongan_id:  # 公安备案号
    gongan_num:  # 公安备案完整编号
    gongan_icon_url:  # 公安备案图标地址

# ---------------------------------------------------------------
# 文章设置
# ---------------------------------------------------------------

# 使用 front-matter 中的 description 作为文章摘要
excerpt_description: true

# 是否显示"阅读更多"按钮
read_more_btn: true

# 文章元信息显示设置
post_meta:
  item_text: true  # 是否显示文本
  created_at: true  # 是否显示创建时间
  updated_at:
    enable: true  # 是否显示更新时间
    another_day: true  # 是否只在日期不同时显示
  categories: true  # 是否显示分类

# 文章字数统计设置
symbols_count_time:
  time: true # 显示帖子的预计阅读时间
  separated_meta: true  # 是否显示分隔符
  item_text_total: true  # 是否显示文字总数

  # item_text_mins: true # 显示帖子的预计阅读时间
  total_symbols: true # 显示帖子的总字数
  # total_time: true # 显示帖子的总阅读时间

# 阅读进度条设置
reading_progress:
  enable: true # 是否启用阅读进度条
  # Available values: left | right
  start_at: left # 阅读进度条位置：left(左侧)|right(右侧)
  # Available values: top | bottom
  position: top # 阅读进度条位置：top(顶部)|bottom(底部)
  reversed: false # 阅读进度条是否反转
  color: "#37c6c0" # 阅读进度条颜色
  height: 2px # 阅读进度条高度

# 书签设置
bookmark:
  enable: false # 是否启用书签
  # 自定义书签的颜色
  color: "#222" # 书签颜色
  # 如果设置为auto,关闭页面或点击书签图标时会保存阅读进度
  # 如果设置为manual,只有点击书签图标时才会保存阅读进度
  save: auto # 阅读进度保存方式：auto(自动保存)|manual(手动保存)


# 是否使用图标代替标签符号 #
tag_icon: false

# 打赏设置
reward_settings:
  enable: true  # 是否启用打赏功能
  animation: true  # 是否启用动画效果

# 打赏按钮图片设置
reward:
  wechatpay: /images/wechatpay.png  # 微信支付二维码
  #alipay: /images/alipay.png  # 支付宝二维码


# 文章编辑设置
post_edit:
  enable: false # 用户可以在 GitHub 上快速浏览和修改博客的源代码。

# 文章导航
post_navigation: left # 文章导航位置：left(左侧)|right(右侧)|none(不显示) 帖子页脚中显示上一篇文章和下一篇文章。

# github 横幅
github_banner:
  enable: true # 是否启用 github 横幅
  permalink: https://github.com/sian-siyu/sian-siyu.github.io/ # 横幅链接
  title: 我的 GitHub # 横幅标题
# ---------------------------------------------------------------
# 数学公式渲染支持
# ---------------------------------------------------------------

math:
  every_page: true  # 是否在每个页面都加载数学公式支持
  mathjax:
    enable: true  # 启用 MathJax
    tags: none  # 公式标签支持级别

# ---------------------------------------------------------------
# 评论系统设置
# ---------------------------------------------------------------

comments:
  style: tabs  # 评论系统显示样式：tabs(标签页)|buttons(按钮)
  active:  # 默认显示的评论系统
  storage: true  # 是否记住用户选择的评论系统
  lazyload: false  # 是否延迟加载评论系统

# ---------------------------------------------------------------
# 统计与分析设置
# ---------------------------------------------------------------

# Google Analytics 设置
google_analytics:
  tracking_id:  # 跟踪ID
  only_pageview: false  # 是否仅统计页面浏览量

# 百度统计设置
baidu_analytics:  # 统计ID

# ---------------------------------------------------------------
# 搜索服务设置
# ---------------------------------------------------------------

# 本地搜索设置
local_search:
  enable: false  # 是否启用本地搜索
  top_n_per_article: 1  # 每篇文章显示的结果数量
  unescape: false  # 是否解码HTML
  preload: false  # 是否预加载搜索数据

# ---------------------------------------------------------------
# CDN设置
# ---------------------------------------------------------------

vendors:
  internal: local  # 内部脚本CDN提供商
  plugins: cdnjs  # 第三方插件CDN提供商
  custom_cdn_url:  # 自定义CDN地址

# 资源文件路径设置
css: css
js: js
images: images
